version: '3.9'

services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: db
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
    - /home/tofig/Downloads/dbdata:/data/db

  goapp:
    build: ./surl-backend
    depends_on:
    - mongodb
    ports:
    - 4000:4000

  frontend:
    build: ./surl-frontend
    ports:
    - 3000:3000
    depends_on:
    - goapp
